//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Webapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int P_Id { get; set; }
        public int U_Id { get; set; }
        public string P_Name { get; set; }
        public string P_Category { get; set; }
        public decimal P_Price { get; set; }
        public int P_Quantity { get; set; }
        public string P_Srt_Desc { get; set; }
        public string P_Lng_Desc { get; set; }
        public string P_sm_img_path { get; set; }
        public string P_lg_img_path { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
